version: '3'
services:
  web:
    build: .
    container_name: ticketmain_app
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://ticketmain_user:password@db:5432/ticketmain_db
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: ticketmain_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ticketmain_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ticketmain_db

volumes:
  postgres_data:
